site_name: Open Mfantse
site_url: https://www.mfantse.com

# Repository
repo_name: mfantse/mfantse
repo_url: https://github.com/mfantse/mfantse

# Copyright
copyright: Copyright &copy; 2023 Enoch T. Enchill

plugins:
  - search
  - mkdocstrings

nav:
  - Nyienyim: 'index.md'
  - Adzesua:
    - Adzesua: 'adzesua/index.md'
    - Ahyɛse: 'adzesua/ahyɛse.md'
    - Anokasadwin: 'adzesua/anokasadwin.md'
    - 'Amambra na Amandze': 'adzesua/amambra.md'
    - 'Mfantsefo Afahyɛ': 'adzesua/afahyɛ.md'
    - 'Mfantse Na Brɔfo': 'adzesua/brɔfo.md'
  - Nkasafua:
    - Nkasafua: nkasafua/index.md
    - A: nkasafua/a.md
    - B: nkasafua/b.md
    - D: nkasafua/d.md
    - E: nkasafua/e.md
    - Ɛ: nkasafua/ɛ.md
    - F: nkasafua/f.md
    - G: nkasafua/g.md
    - H: nkasafua/h.md
    - I: nkasafua/i.md
    - J: nkasafua/j.md
    - K: nkasafua/k.md
    - L: nkasafua/l.md
    - M: nkasafua/m.md
    - N: nkasafua/n.md
    - O: nkasafua/o.md
    - Ɔ: nkasafua/ɔ.md
    - P: nkasafua/p.md
    - R: nkasafua/r.md
    - S: nkasafua/s.md
    - T: nkasafua/t.md
    - U: nkasafua/u.md
    - W: nkasafua/w.md
    - Y: nkasafua/y.md
    - Z: nkasafua/z.md
  - Adowno:
    - Adowno: adowno/index.md
    - Ahyɛse: adowno/ahyɛse.md
    - Akwantu: adowno/akwantu.md
    - Asɔfo: adowno/asɔfo.md
    - Nkanee: adowno/nkanee.md
    - Asafo: adowno/asafo.md
    - Ahenfo: adowno/ahenfo.md
    - Amambu: adowno/amambu.md
    - Amandze: adowno/amandze.md
    - Gyedzi: adowno/gyedzi.md
    - Kodzisɛm: adowno/kodzisɛm.md
    - Mbɛbusɛm: adowno/mbɛbusɛm.md
    - Kasambirenyi: adowno/kasambirenyi.md
    - Nkanyan: adowno/nkanyan.md
    - Nyimdzee: adowno/nyimdzee.md
    - Ndwuma: adowno/ndwuma.md
    - Nhyira: adowno/nhyira.md
    - Nkonyim: adowno/nkonyim.md
    - Ahenmaa: adowno/ahenmaa.md
  - Baebor:
    - Baebor: baebor/index.md
    - Gyenesis: baebor/gen.md
    - Eksodɔs: baebor/exo.md
    - Levitikɔs: baebor/lev.md
    - Nkanee: baebor/num.md
    - Deuteronomi: baebor/deu.md
    - Josua: baebor/jos.md
    - Atsɛmbuafo: baebor/jdg.md
    - Rut: baebor/rut.md
    - "1 Samuel": baebor/1sa.md
    - "2 Samuel": baebor/2sa.md
    - "1 Ahemfo": baebor/1ki.md
    - "2 Ahemfo": baebor/2ki.md
    - "1 Mbermunsɛm": baebor/1ch.md
    - "2 Mbermunsɛm": baebor/2ch.md
    - Ezra: baebor/ezr.md
    - Nehemia: baebor/neh.md
    - Ester: baebor/est.md
    - Job: baebor/job.md
    - Ndwom: baebor/psa.md
    - Mbɛbusɛm: baebor/pro.md
    - Ɔsɛnkafo: baebor/ecc.md
    - "Ndwom mu Ndwom": baebor/sng.md
    - Isaia: baebor/isa.md
    - Jeremia: baebor/jer.md
    - Kwadwom: baebor/lam.md
    - Ezekiel: baebor/ezk.md
    - Daniel: baebor/dan.md
    - Hosea: baebor/hos.md
    - Joel: baebor/jol.md
    - Amos: baebor/amo.md
    - Obadia: baebor/oba.md
    - Jona: baebor/jon.md
    - Mika: baebor/mic.md
    - Nahum: baebor/nam.md
    - Habakuk: baebor/hab.md
    - Zefania: baebor/zep.md
    - Hagai: baebor/hag.md
    - Zekaria: baebor/zec.md
    - Malaki: baebor/mal.md
    - Matthew: baebor/mat.md
    - Mark: baebor/mrk.md
    - Luke: baebor/luk.md
    - John: baebor/jhn.md
    - Ndwuma: baebor/act.md
    - Romefo: baebor/rom.md
    - "1 Korintefo": baebor/1co.md
    - "2 Korintefo": baebor/2co.md
    - Galatiafo: baebor/gal.md
    - Efesofo: baebor/eph.md
    - Filipifo: baebor/php.md
    - Kolosaefo: baebor/col.md
    - "1 Tesalonikafo": baebor/1th.md
    - "2 Tesalonikafo": baebor/2th.md
    - "1 Timoti": baebor/1ti.md
    - "2 Timoti": baebor/2ti.md
    - Titus: baebor/tit.md
    - Faelemɔn: baebor/phm.md
    - Hebriwfo: baebor/heb.md
    - James: baebor/jas.md
    - "1 Peter": baebor/1pe.md
    - "2 Peter": baebor/2pe.md
    - "1 John": baebor/1jn.md
    - "2 John": baebor/2jn.md
    - "3 John": baebor/3jn.md
    - Jude: baebor/jud.md
    - Nyikyerɛ: baebor/rev.md

theme:
  name: material
  features:
    - announce.dismiss
    # - content.action.edit
    # - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo
markdown_extensions:
  - tables
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg